Update classroom.yml

diff --git a/.github/workflows/classroom.yml b/.github/workflows/classroom.yml
--- a/.github/workflows/classroom.yml
+++ b/.github/workflows/classroom.yml
@@ -32,12 +32,12 @@ jobs:
           echo "Listing test files:"
           ls -R test
 
-      - name: Run tests
-        id: run-tests
-        run: |
-          # Run tests with mocha directly
-          ./node_modules/.bin/mocha --require @babel/register --reporter mocha-junit-reporter test/**/*.js > test-results.xml || { echo "Test command failed"; exit 1; }
-          echo "Test results saved to test-results.xml."
+- name: Run tests
+  id: run-tests
+  run: |
+    ./node_modules/.bin/mocha --require @babel/register --reporter mocha-junit-reporter --verbose test/**/*.js > test-results.xml || { cat test-results.xml; echo "Test command failed"; exit 1; }
+    echo "Test results saved to test-results.xml."
+
 
       - name: Install xmlstarlet
         run: sudo apt-get install -y xmlstarlet
